[package]
name = "smartcontract_bootstrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# clap = { version = "4.0.15", features = ["derive"] }
clap = {version = "3.0.0-beta.1", features = ["yaml"]}
indicatif = "0.17.2"
handlebars = "4.3.6"
serde_json = "1.0.91"
spinoff = "0.6.0"
